# Check out https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/ for more information
workflows:
  flutter-android:
    name: Flutter Android
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - google_play # Optional
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - du96004-lgtm@users.noreply.github.com

  flutter-ios:
    name: Flutter iOS
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          flutter create .
      - name: Precache iOS artifacts
        script: flutter precache --ios
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - du96004-lgtm@users.noreply.github.com
