// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOrFFRMy-ZvX6nEB-X9D0N8zXCcQjlWS0',
    appId: '1:6695969774:android:8edac2fd310c77625a24ff',
    messagingSenderId: '6695969774',
    projectId: 'secretchat-e7563',
    databaseURL: 'https://secretchat-e7563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretchat-e7563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvvgfGqwb26VvnLTZxRYYGA_-tL50CDE',
    appId: '1:6695969774:ios:111f93ea2ef44d715a24ff',
    messagingSenderId: '6695969774',
    projectId: 'secretchat-e7563',
    databaseURL: 'https://secretchat-e7563-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'secretchat-e7563.firebasestorage.app',
    androidClientId: '6695969774-qdj5caaavau4b1pso723ap72dc0gtb5r.apps.googleusercontent.com',
    iosClientId: '6695969774-5i88u2dnsvvv3iohhk1jq7k16itr2c4v.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.secretchat.secretchat',
  );

}