# The next line is used by fastlane to identify the step.
# @target_sdk: ios

platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronous priority.
# Disable this for faster builds.
install! 'cocoapods', :deterministic_uuids => false

load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
